version :0.1

phases:
  build:
    commands :
    - echo Entered the build phase..
    - mvn clean package
  post_build:
    commands :
      -echo Build completed successfully
artifacts:
  files :
    target/demo-0.0.1-SNAPSHOT.jar
  discards-paths: yes